import { ArchitectureFlow,Block,Callout,CodeBlock,ConceptGrid } from './ui';
import { FundamentalsDemo } from './fundamentals-demo';
import { RagDemo } from './rag-demo';
import { ReliabilityDemo } from './reliability-demo';
import { ToolsDemo, AgentDemo } from './execution-demo';
export function LessonContent({index}:{index:number}){return [<Foundations key="1"/>,<Rag key="2"/>,<Reliability key="3"/>,<Tools key="4"/>,<Agents key="5"/>][index]}
function Foundations(){return <>
<Block eyebrow="EL PUNTO DE PARTIDA" title="Una respuesta convincente puede ser incorrecta."><p>Le pides a una IA el horario de una empresa. Responde con seguridad, pero ese horario no aparece en ningún lugar del contexto. ¿De dónde ha salido?</p><p>Un <strong>modelo de lenguaje —LLM—</strong> aprende patrones a partir de texto. Al generar, calcula qué token puede continuar la secuencia disponible. Esa operación, repetida, produce una respuesta. No verifica por sí sola que los hechos sean ciertos.</p><Callout>Un LLM, por sí solo, no consulta una base de datos cuando responde. Una aplicación puede conectarlo a búsqueda, documentos y herramientas.</Callout></Block>
<Block eyebrow="DEL INPUT AL OUTPUT" title="Una secuencia. Muchas decisiones."><p>El modelo recibe una representación del texto, procesa sus relaciones y calcula una distribución de probabilidades. Cada token elegido se añade al contexto para generar el siguiente.</p><ArchitectureFlow steps={[{name:'Prompt',detail:'Instrucciones y texto'},{name:'Tokens',detail:'Unidades del vocabulario'},{name:'Contexto',detail:'Información disponible'},{name:'Transformer',detail:'Relaciones entre tokens'},{name:'Probabilidades',detail:'Posibles continuaciones'},{name:'Respuesta',detail:'Generación paso a paso'}]}/><p className="fine-print">Esquema conceptual de un Transformer generativo. La tokenización y la representación numérica preceden al procesamiento.</p></Block>
<FundamentalsDemo/>
<Block eyebrow="DENTRO DEL MODELO" title="Representar y relacionar."><ConceptGrid items={[{name:'Tokens',text:'Piezas del vocabulario: pueden ser palabras, partes de palabras, espacios o signos. Una palabra no equivale necesariamente a un token.'},{name:'Embeddings',text:'Representaciones numéricas que permiten al modelo trabajar con tokens. Un embedding de búsqueda puede representar un fragmento completo.'},{name:'Transformer',text:'Arquitectura que transforma las representaciones del contexto mediante capas. Es la base de muchos modelos de lenguaje actuales.'},{name:'Attention',text:'Mecanismo que pondera cómo unas posiciones del texto aportan información a otras. Ayuda a relacionar, por ejemplo, un pronombre con su referente.'}]}/><Callout title="UNA RELACIÓN, NO CONSCIENCIA">En «Lucía dejó la mochila porque estaba rota», las relaciones del contexto ayudan a asociar «rota» con «mochila». Attention es una operación numérica, no atención humana.</Callout></Block>
<Block eyebrow="EL LÍMITE DEL CONTEXTO" title="Lo que no recibe, puede faltar."><p>La ventana de contexto tiene un límite de tokens. Instrucciones, historial, documentos y resultado comparten un presupuesto que depende del modelo. Una conversación larga puede requerir selección o resumen.</p><p>Un modelo puede generar hechos falsos, mezclar información o inventar una fuente: llamamos <strong>alucinación</strong> a este tipo de salida. Una frase probable no tiene por qué ser verdadera.</p><CodeBlock code={'contexto = [instrucciones, historial, pregunta]\nwhile not terminado:\n    probabilidades = modelo(contexto)\n    token = seleccionar(probabilidades)\n    contexto.append(token)\n    emitir(token)'}/></Block>
<Block eyebrow="CASO DE USO" title="El modelo es una pieza. La aplicación es el sistema."><p>Un asistente de soporte necesita más que buena redacción: documentos actualizados, acceso al pedido, reglas de devolución y controles antes de modificar una cuenta.</p><ConceptGrid items={[{name:'Modelo',text:'Procesa contexto y genera una salida. No es, por sí mismo, una fuente fiable del estado de tus operaciones.'},{name:'Aplicación',text:'Construye el contexto, llama al modelo, valida la respuesta, gestiona permisos y decide qué mostrar o ejecutar.'}]}/><Callout>Para responder sobre una política privada, primero debes proporcionar esa política. En la siguiente lección construiremos ese recorrido.</Callout></Block>
</>}
function Rag(){return <>
<Block eyebrow="EL PROBLEMA REAL" title="La respuesta está en tus documentos."><p>Tienes cientos de documentos: procedimientos, fichas y políticas. Quieres que una IA encuentre la información correcta y responda usando ese conocimiento.</p><p>Enviar todo en cada consulta consume contexto y añade ruido. <strong>RAG —Retrieval-Augmented Generation—</strong> separa el trabajo: primero recupera evidencia relevante; después genera una respuesta con esa evidencia.</p><Callout>RAG no entrena de nuevo el modelo. Le proporciona conocimiento en el momento de responder. Reduce algunos errores, pero no garantiza respuestas correctas.</Callout></Block>
<Block eyebrow="REPRESENTACIÓN" title="Buscar por significado."><p>Un embedding convierte un texto en un <strong>vector</strong>: una lista de números. Un modelo de embeddings coloca textos relacionados cerca según una medida de similitud, como el coseno.</p><div className="semantic-map"><div className="map-axis label">ESPACIO SEMÁNTICO · PROYECCIÓN ILUSTRATIVA</div><div className="semantic-cluster"><span>● ¿Puedo devolverlo?</span><span>● Política de devoluciones</span><span>● Reembolsos</span></div><div className="semantic-far">● Instalación del producto</div><div className="map-caption">Cercanía semántica ≠ palabras idénticas</div></div><p className="fine-print">El dibujo usa dos dimensiones por claridad. Los embeddings reales suelen tener muchas más; proximidad no implica veracidad.</p></Block>
<Block eyebrow="PREPARAR EL CONOCIMIENTO" title="Una biblioteca que se puede consultar."><ArchitectureFlow label="INDEXACIÓN · CUANDO CAMBIAN LOS DOCUMENTOS" steps={[{name:'Documentos',detail:'Limpiar y versionar'},{name:'Chunks',detail:'Fragmentos con sentido'},{name:'Embeddings',detail:'Un vector por fragmento'},{name:'Vector database',detail:'Vectores + texto + metadatos'}]}/><p className="fine-print">Los chunks conservan la fuente, fecha, sección y permisos. La base vectorial permite encontrar vecinos similares; el texto original sigue siendo necesario.</p></Block>
<Block eyebrow="RESPONDER CON EVIDENCIA" title="La consulta sigue otro camino."><ArchitectureFlow label="CONSULTA · CADA PREGUNTA" steps={[{name:'Pregunta',detail:'Qué necesita el usuario'},{name:'Embedding',detail:'Modelo compatible con el índice'},{name:'Búsqueda',detail:'Vecinos + filtros de acceso'},{name:'Fragmentos',detail:'Evidencia seleccionada'},{name:'Contexto + LLM',detail:'Instrucciones y fuentes'},{name:'Respuesta',detail:'Citas y límites claros'}]}/><Callout title="DOS MOMENTOS DIFERENTES">Indexar organiza los documentos. Consultar selecciona los fragmentos útiles para una pregunta concreta. Actualizar los documentos también exige actualizar el índice.</Callout></Block>
<RagDemo/>
<Block eyebrow="LA LÓGICA MÍNIMA" title="Recuperar antes de generar."><CodeBlock code={'vector = embed(pregunta)\nfragmentos = buscar(vector, top_k=4, permisos=usuario)\nif not evidencia_suficiente(fragmentos):\n    return "No tengo información suficiente"\ncontexto = unir_texto_y_fuentes(fragmentos)\nrespuesta = generar(\n    pregunta=pregunta, contexto=contexto,\n    instrucciones="Responde con fuentes; no inventes"\n)\nreturn validar_citas(respuesta, fragmentos)'}/><p className="fine-print">El umbral de evidencia debe evaluarse en tu conjunto de datos. Un porcentaje de similitud no es una probabilidad de que la respuesta sea correcta.</p></Block>
<Block eyebrow="CASO DE USO" title="Un asistente interno de operaciones."><p>Una persona pregunta cómo tramitar una devolución. El sistema recupera el procedimiento vigente y cita la sección exacta. Si falta la política o hay versiones contradictorias, lo comunica y deriva la consulta.</p><ConceptGrid items={[{name:'Qué guardar',text:'Texto limpio, ID de fuente, versión, fecha de actualización y permisos. Sin trazabilidad, una respuesta plausible es difícil de auditar.'},{name:'Qué comprobar',text:'Que los fragmentos respondan a la pregunta y que la respuesta esté respaldada por ellos. Evalúa retrieval y generación por separado.'}]}/><Callout>Un buen modelo no puede compensar indefinidamente una mala recuperación. Ahora ajustaremos qué información llega al contexto.</Callout></Block>
</>}
function Reliability(){return <>
<Block eyebrow="DE DEMO A SISTEMA" title="Una prueba que sale bien no basta."><p>Tu asistente responde diez preguntas. Una sale perfecta; tres mezclan políticas antiguas; otra devuelve un formato imposible de procesar. La calidad del sistema no es la calidad de su mejor ejemplo.</p><p>La fiabilidad requiere <strong>datos cuidados, recuperación relevante, salidas controladas y pruebas repetibles</strong>. Cambia una variable cada vez y compara siempre las mismas preguntas.</p></Block>
<Block eyebrow="LAS PALANCAS" title="Más contexto no siempre ayuda."><ConceptGrid items={[{name:'Chunk size',text:'Tamaño de cada fragmento. Uno pequeño puede perder información; uno grande puede mezclar temas. Busca unidades con sentido antes de elegir un número.'},{name:'Chunk overlap',text:'Parte que comparten fragmentos consecutivos. Ayuda a conservar relaciones en los bordes, pero demasiado solapamiento duplica contenido.'},{name:'Top-k',text:'Cuántos candidatos recuperas. Un k alto aumenta cobertura y coste; también puede añadir ruido. Ajusta según tus preguntas.'},{name:'Reranking',text:'Un segundo paso reordena los candidatos según su relevancia para la pregunta. Puede mejorar la selección, a cambio de latencia y coste.'}]}/></Block>
<ReliabilityDemo/>
<Block eyebrow="CALIDAD Y EVALUACIÓN" title="Mide el fallo que importa."><p>Prepara preguntas representativas con sus fuentes esperadas. Incluye preguntas sin respuesta, documentos desactualizados, ambigüedades y usuarios sin acceso.</p><div className="table-wrap"><table><thead><tr><th>Qué evalúas</th><th>Cómo lo compruebas</th></tr></thead><tbody><tr><td>Recuperación</td><td>¿Está el fragmento necesario entre los resultados?</td></tr><tr><td>Fidelidad</td><td>¿Cada afirmación está respaldada por una fuente?</td></tr><tr><td>Abstención</td><td>¿Reconoce que falta información?</td></tr><tr><td>Operación</td><td>¿Cumple formato, permisos, coste y latencia?</td></tr></tbody></table></div><Callout title="UN ERROR FRECUENTE">Un mejor resultado en diez preguntas no demuestra una mejora general. Conserva un conjunto de evaluación separado y revisa los errores, no solo la media.</Callout></Block>
<Block eyebrow="STRUCTURED OUTPUT" title="El software necesita contratos."><p>«Pedro García trabaja en Acme y su email es pedro@acme.com» es comprensible para una persona. Una integración necesita campos definidos, tipos y validación.</p><CodeBlock caption="Salida estructurada · JSON" code={'{\n  "nombre": "Pedro García",\n  "empresa": "Acme",\n  "email": "pedro@acme.com"\n}'}/><p className="fine-print">Un schema define los campos y sus tipos. La salida debe superar la validación antes de que otra parte del sistema la utilice.</p><CodeBlock caption="Contrato mínimo · JSON Schema" code={'{\n  "type": "object",\n  "properties": {\n    "nombre": { "type": "string" },\n    "empresa": { "type": "string" },\n    "email": { "type": "string", "format": "email" }\n  },\n  "required": ["nombre", "empresa", "email"],\n  "additionalProperties": false\n}'}/><Callout title="FORMATO NO ES VERDAD">Un JSON válido puede contener datos falsos. Valida también el significado, activa la validación de formatos del validador y contrasta los campos con la fuente.</Callout></Block>
<Block eyebrow="CASO DE USO" title="De un email a una ficha de CRM."><p>El sistema extrae los campos, valida el schema y comprueba si el contacto ya existe. Si el email falta o es ambiguo, lo marca para revisión; no lo inventa.</p><CodeBlock code={'datos = extraer(email, schema=ContactSchema)\nvalidar_schema(datos)\nvalidar_contra_fuente(datos, email)\nif hay_ambiguedad(datos):\n    return enviar_a_revision(datos)\nguardar_contacto(datos, clave_idempotente=email.id)'}/><Callout>Primero define qué significa «correcto». Después escribe las pruebas que detectan cuándo deja de serlo.</Callout></Block>
</>}
function Tools(){return <>
<Block eyebrow="DEL TEXTO A LA ACCIÓN" title="Una IA no crea una tarea por decirlo."><p>«He creado la tarea» puede ser solo una frase. Para que exista en tu CRM, una aplicación debe ejecutar una operación y comprobar su resultado.</p><ArchitectureFlow label="LLM SIN HERRAMIENTAS" steps={[{name:'Usuario',detail:'Hace una petición'},{name:'LLM',detail:'Genera una respuesta'},{name:'Texto',detail:'Ningún cambio externo'}]}/><Callout>El modelo propone una llamada. La aplicación valida los argumentos y permisos, ejecuta la herramienta y devuelve el resultado al modelo.</Callout></Block>
<Block eyebrow="EL BUCLE DE HERRAMIENTAS" title="Decidir, ejecutar, observar."><ArchitectureFlow steps={[{name:'Usuario + LLM',detail:'Interpreta el objetivo'},{name:'Tool call',detail:'Nombre y argumentos'},{name:'Aplicación',detail:'Valida y autoriza'},{name:'Sistema externo',detail:'Ejecuta vía API'},{name:'Resultado',detail:'Datos o error'},{name:'LLM → respuesta',detail:'Explica lo que ocurrió'}]}/><p className="fine-print">Una API puede fallar. La respuesta final debe reflejar el resultado real de cada acción, incluyendo fallos parciales.</p></Block>
<ToolsDemo/>
<Block eyebrow="EL CONTRATO" title="Una herramienta es una capacidad limitada."><CodeBlock caption="Tool call · propuesta del modelo" code={'{\n  "name": "crear_tarea",\n  "arguments": {\n    "cliente_id": "CLI-1042",\n    "titulo": "Llamar por facturas pendientes",\n    "fecha": "2026-10-01"\n  }\n}'}/><p className="fine-print">Fecha ilustrativa. En producción, resuelve «mañana» con la zona horaria del usuario, valida el cliente y evita tareas duplicadas al reintentar.</p><ConceptGrid items={[{name:'Function calling',text:'El modelo expresa una llamada con nombre y argumentos estructurados. El código de la aplicación se encarga de ejecutarla.'},{name:'API',text:'Interfaz de un sistema externo. Una herramienta adapta esa interfaz a una operación concreta y controlada.'},{name:'Memoria',text:'Información persistida y recuperada por la aplicación entre interacciones. No implica que el modelo recuerde todo por sí solo.'},{name:'Permisos',text:'Cada acción se ejecuta con los permisos del usuario o servicio. El modelo no debe poder ampliarlos.'}]}/></Block>
<Block eyebrow="MCP, SIN MISTERIO" title="Una forma consistente de conectar."><p><strong>Model Context Protocol</strong> es un estándar para conectar aplicaciones de IA con herramientas y fuentes externas. Un cliente MCP dentro de la aplicación se comunica con un servidor que expone capacidades.</p><ArchitectureFlow label="CONEXIÓN MCP · VISTA CONCEPTUAL" steps={[{name:'Aplicación de IA',detail:'Host con cliente MCP'},{name:'Servidor MCP',detail:'Expone herramientas y recursos'},{name:'Sistemas',detail:'CRM, documentos, servicios'}]}/><Callout>MCP estandariza la conexión; no reemplaza las APIs del negocio, la autorización ni los controles sobre lo que se ejecuta.</Callout></Block>
<Block eyebrow="CASO DE USO" title="Cobros con trazabilidad."><p>Buscar al cliente y consultar sus facturas son lecturas. Crear una tarea es una escritura. Registra ambas, pero valida especialmente las acciones que cambian datos.</p><p>Si la consulta de facturas falla, no asumas que el saldo es cero. Si hay dos personas con el mismo nombre, solicita un identificador antes de crear la tarea.</p><Callout>Una herramienta bien definida hace menos cosas, pero permite saber exactamente qué ocurrió.</Callout></Block>
</>}
function Agents(){return <>
<Block eyebrow="UNIR LAS PIEZAS" title="Un agente no es un robot mágico."><p>Es un sistema en el que un modelo decide pasos o herramientas para perseguir un objetivo, observando los resultados y operando dentro de límites.</p><div className="agent-equation">LLM <span>+</span> instrucciones <span>+</span> contexto <span>+</span> herramientas <span>+</span> estado</div><ConceptGrid items={[{name:'Workflow',text:'Los pasos y las transiciones los define el código. Útil cuando el proceso es conocido y necesitas previsibilidad.'},{name:'Agente',text:'El modelo elige parte del recorrido según lo que observa. Útil con variabilidad, pero requiere más evaluación y límites.'}]}/><Callout>Empieza con un workflow cuando conoces el proceso. Añade autonomía solo donde aporte valor medible.</Callout></Block>
<Block eyebrow="UN PROCESO REAL" title="Preparar una reunión comercial."><p>Partimos de la URL de una empresa. Buscamos información, analizamos su actividad, planteamos hipótesis de mejora y redactamos un briefing para revisión humana.</p><ArchitectureFlow steps={[{name:'URL de empresa',detail:'Entrada validada'},{name:'Obtener información',detail:'Fuentes identificadas'},{name:'Analizar empresa',detail:'Hechos y contexto'},{name:'Detectar oportunidades',detail:'Hipótesis, no certezas'},{name:'Generar briefing',detail:'Salida estructurada'},{name:'Revisar resultado',detail:'Control humano'}]}/></Block>
<AgentDemo/>
<Block eyebrow="ESTADO Y CONTROL" title="Saber dónde está el proceso."><p>El estado conserva lo que ya se ha hecho: fuentes, resultados, errores, coste y siguiente paso. Permite reanudar el proceso sin repetir acciones con efectos externos.</p><CodeBlock code={'estado = iniciar(objetivo, max_pasos=6)\nwhile not estado.terminado:\n    paso = decidir_siguiente(estado)\n    validar_permisos_y_presupuesto(paso)\n    resultado = ejecutar(paso)\n    estado = registrar(estado, paso, resultado)\n    if resultado.requiere_revision:\n        return pausar_para_revision(estado)'}/><Callout title="LÍMITES EXPLÍCITOS">Define un máximo de pasos, tiempo y coste. Añade reintentos acotados, registros de cada llamada y revisión antes de acciones irreversibles.</Callout></Block>
<Block eyebrow="LA ARQUITECTURA COMPLETA" title="La respuesta es el resultado de un sistema."><div className="system-architecture"><div className="system-user">USUARIO</div><div className="vertical-connector">↓</div><div className="system-main"><div className="label">SISTEMA DE IA</div><h3>Modelo + instrucciones + controles</h3><div className="system-capabilities">{['RAG','TOOLS','APIs','WEB','DATABASE','MEMORIA'].map(t=><span key={t}>{t}</span>)}</div><p>Capacidades disponibles según permisos y necesidad</p></div><div className="vertical-connector">↓</div><div className="system-pair"><span>WORKFLOW / AGENTE<small>Coordina pasos y conserva estado</small></span><span>RESULTADO<small>Validado, trazable y revisable</small></span></div></div><p className="fine-print">Las capacidades no son independientes por obligación: una tool puede consultar una API, y RAG puede utilizar una base de datos. El diagrama muestra responsabilidades, no servicios que debas desplegar por separado.</p></Block>
<Block eyebrow="ELEGIR CON CRITERIO" title="¿Qué pieza necesitas realmente?"><div className="decision-list">{[['Cambiar instrucciones','PROMPT','Define tarea, límites y ejemplos.'],['Aportar conocimiento privado','RAG','Recupera evidencia actualizada y autorizada.'],['Obtener datos con un contrato','STRUCTURED OUTPUT','Controla tipos, campos y validación.'],['Consultar o modificar sistemas','TOOLS','Expone operaciones con permisos concretos.'],['Ejecutar un proceso de varios pasos','WORKFLOW / AGENTE','Coordina operaciones; decide cuánta autonomía necesitas.'],['Adaptar un comportamiento especializado','FINE-TUNING','Evalúalo si instrucciones y ejemplos no bastan; requiere datos y evaluación.']].map(([need,tool,desc])=><div key={tool}><p>{need}<small>{desc}</small></p><span>{tool}</span></div>)}</div><Callout title="CIERRE DEL RECORRIDO">Elige la arquitectura más simple que resuelva el problema y puedas evaluar. Un sistema útil combina conocimiento, acciones y controles; no necesita todas las piezas a la vez.</Callout></Block>
</>}
