'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { lessons } from '@/lib/lessons';
function usePresentation(){const [present,setPresent]=useState(false);useEffect(()=>{const sync=()=>setPresent(new URLSearchParams(window.location.search).get('present')==='true');sync();window.addEventListener('popstate',sync);window.addEventListener('presentationchange',sync);return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('presentationchange',sync)}},[]);return present}
export function PresentationLink({href,children,...props}:{href:string;children:React.ReactNode;className?:string}){const present=usePresentation();return <Link {...props} href={href+(present?'?present=true':'')}>{children}</Link>}
export function Shell({children,index}:{children:React.ReactNode;index?:number}){
 const [present,setPresent]=useState(false);
 useEffect(()=>{const sync=()=>setPresent(new URLSearchParams(window.location.search).get('present')==='true');sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 const suffix=present?'?present=true':'';
 function toggle(){const value=!present;setPresent(value);const url=new URL(window.location.href);if(value)url.searchParams.set('present','true');else url.searchParams.delete('present');window.history.replaceState(null,'',url);window.dispatchEvent(new Event('presentationchange'))}
 return <div className={present?'site presentation':'site'}><a className="skip-link" href="#contenido">Saltar al contenido</a><header className="site-header"><Link href={'/'+suffix} className="brand" aria-label="La Nueva Industria, inicio"><span className="brand-wordmark"><span>LA NUEVA</span><strong>INDUSTRIA</strong></span></Link><nav aria-label="Navegación principal">{index===undefined?<span className="header-note secondary">CONOCIMIENTO / SISTEMAS</span>:<><Link className="secondary index-link" href={'/lecciones/'+suffix}>Índice</Link><span className="counter">{String(index+1).padStart(2,'0')} <span>/ 05</span></span>{index>0&&<Link className="secondary" href={'/lecciones/'+lessons[index-1].slug+'/'+suffix}>Anterior</Link>}{index<4&&<Link href={'/lecciones/'+lessons[index+1].slug+'/'+suffix}>Siguiente <span aria-hidden="true">↗</span></Link>}</>}<button className="present-button" onClick={toggle} aria-pressed={present} title="Activar o salir del modo presentación">{present?'Salir de presentación':'Modo presentación'}<span aria-hidden="true">{present?'⊟':'⊞'}</span></button></nav></header><main id="contenido">{children}</main><footer className="site-footer secondary"><span>LA NUEVA INDUSTRIA</span><span>Entender. Construir. Comprobar.</span><span>IA APLICADA / 01—05</span></footer></div>
}
export function LessonFooter({index}:{index:number}){const present=usePresentation();const suffix=present?'?present=true':'';const next=lessons[index+1];return <div className="lesson-footer"><span className="label">{next?'CONTINÚA EL RECORRIDO':'RECORRIDO COMPLETADO'}</span><Link className="next-lesson" href={next?'/lecciones/'+next.slug+'/'+suffix:'/lecciones/'+suffix}><span>{next?<><small>{String(index+2).padStart(2,'0')} / 05</small>{next.short}</>:'Vuelve al mapa completo'}</span><span aria-hidden="true">↗</span></Link><Link className="text-link secondary" href={'/lecciones/'+suffix}>Volver al índice</Link></div>}
