export type Topic='returns'|'shipping'|'warranty'|'payments';
export const questions=['¿Cuándo puedo devolver un producto?','¿Cuánto tarda el envío?','¿Qué cubre la garantía?','¿Cómo puedo pagar?'];
const records:Record<Topic,{terms:string[];docs:{id:string;title:string;score:number;text:string}[];answer:string}>= {
 returns:{terms:['devol','devolver','devuel','retorn','reembolso','arrepent'],docs:[{id:'DEV-01',title:'Política de devoluciones',score:92,text:'Se aceptan devoluciones durante los 30 días naturales desde la entrega. El producto debe estar sin usar y conservar su embalaje. Solicita la devolución desde tu pedido.'},{id:'COND-02',title:'Condiciones generales',score:78,text:'El reembolso se realiza mediante el método de pago original en un máximo de 7 días laborables después de revisar el producto devuelto.'},{id:'FAQ-03',title:'Preguntas frecuentes',score:63,text:'Los artículos personalizados no admiten devolución por cambio de opinión. Contacta con soporte si presentan un defecto.'}],answer:'Puedes solicitar la devolución en los 30 días naturales posteriores a la entrega, siempre que el producto esté sin usar y conserve el embalaje [DEV-01]. Los artículos personalizados no admiten devolución por cambio de opinión [FAQ-03].'},
 shipping:{terms:['envio','entrega','llega','tarda','transporte'],docs:[{id:'ENV-01',title:'Guía de envíos',score:94,text:'Los pedidos estándar se entregan en 2–4 días laborables dentro de la península. El plazo empieza cuando se confirma la expedición.'},{id:'ENV-02',title:'Seguimiento del pedido',score:81,text:'Enviamos un enlace de seguimiento por email al salir el paquete del almacén.'},{id:'FAQ-01',title:'Preguntas frecuentes',score:65,text:'Durante campañas de alta demanda, la entrega puede tardar hasta 2 días laborables adicionales.'}],answer:'La entrega estándar en la península tarda 2–4 días laborables desde la expedición [ENV-01]. En campañas de alta demanda puede sumar hasta 2 días laborables [FAQ-01]. Recibirás un enlace de seguimiento por email [ENV-02].'},
 warranty:{terms:['garantia','defecto','repar','averia','roto'],docs:[{id:'GAR-01',title:'Garantía comercial de ejemplo',score:93,text:'Nuestra garantía comercial ficticia cubre defectos de fabricación. El equipo de soporte revisa el comprobante de compra y fotografías del defecto.'},{id:'GAR-02',title:'Exclusiones de cobertura',score:77,text:'La garantía comercial de este catálogo no cubre golpes, uso incorrecto ni desgaste normal.'},{id:'FAQ-04',title:'Contacto de soporte',score:62,text:'Abre una incidencia desde el área de pedidos y adjunta imágenes del producto.'}],answer:'La garantía comercial del catálogo cubre defectos de fabricación [GAR-01], pero no golpes, uso incorrecto o desgaste normal [GAR-02]. Abre una incidencia y adjunta el comprobante de compra y fotografías [GAR-01, FAQ-04].'},
 payments:{terms:['pag','tarjeta','paypal','transferencia','metodo'],docs:[{id:'PAG-01',title:'Métodos de pago',score:96,text:'La tienda ficticia admite tarjeta de débito, tarjeta de crédito y transferencia bancaria. No admite PayPal ni pago contra reembolso.'},{id:'PAG-02',title:'Confirmación de transferencia',score:79,text:'Los pedidos por transferencia se preparan cuando se confirma el ingreso, normalmente en 1–2 días laborables.'},{id:'FAQ-05',title:'Seguridad del pago',score:60,text:'La tienda no almacena el número completo de tu tarjeta.'}],answer:'Puedes pagar con tarjeta de débito, crédito o transferencia. No se admite PayPal ni contra reembolso [PAG-01]. Si eliges transferencia, el pedido se prepara al confirmar el ingreso, normalmente en 1–2 días laborables [PAG-02].'}
};
export function retrieve(question:string){const q=question.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const topic=(Object.keys(records) as Topic[]).find(t=>records[t].terms.some(k=>q.includes(k)));return topic?records[topic]:null;}
